### ISSUE TITLE
Flannel service is failing

### ISSUE THREAD

**Issue by coolpalani** [skymyyang/salt-k8s-ha#1]
Hi,

Could you explain about VIP IP Address concept which you were using in this deployment model.

https://github.com/skymyyang/salt-k8s-ha/blob/master/salt/k8s/modules/flannel.sls#L57

when flannel service is trying to bring up through salt, it's failing due to unavailable of VIP in the specific NIC on master server. Are you attaching secondary NIC card in the master and assigning ip address as 192.168.150.253 if so when first master going down then how service request will continue to serve from other masters.

**Comment by skymyyang** [comment]
Here'vip_if'refers to the name of the network card; 'VIP IP' is suitable for haproxy and is not used for load balancing with nginx. There is no deletion here.

**Comment by sky-daiji** [comment]
no problem！
